### ISSUE TITLE
Keil RTX OS component

### ISSUE THREAD

**Issue by somogyitibor** [ErichStyger/McuOnEclipse_PEx#14]
Hello,
I try to continue to use PEx... and I just learnt ( well, I am late :-) ) that Keil's RTX is open sourced since 2012... so, I thought that I could use under KDE/PEx... However
1/ The available OS components do not include RTX
2/ Seems that I am not allowed to create an "OS class" component with my KDE without "a professional license" of the CDE. I have your Community Edition license.dat file, but it seems not to work...
So, could you, please
- either create an OS type PEx component for Keil's RTX ( like your FreeRTOS component ) and make it public here ( you can download KeilRTX from https://www.keil.com/demo/eval/rtx.htm ) 
- or advise how I can create this component on my own... ( if you have an idea about how to obtain a "professional license" for CDE under KDE, please let me know it. )
 Thanks and regards
Tibor

**Comment by ErichStyger** [comment]
Hi Tibor,
Yes, I'm not aware of any RTX Processor Expert component. 
I won't use RTX in my projects because I have no use for it, and FreeRTOS in my own view is superior and much easier to use. That's probably why ARM stopped making money with RTX.
To create an OS component you do not only need a Professional Edition License, you need a special one to create OS components. Actually you don't really need one (I did not had one): you can create an OS component without it if you are willing to use a normal text editor for a few files and not using the graphical Bean wizard. You can find CDE articles under https://mcuoneclipse.com/tag/cde/  and https://mcuoneclipse.com/2012/06/30/the-making-of-rtos-processor-expert-components/ some pointers how to do it. Best if you use my FreeRTOS component as a reference.

Good luck!

**Comment by somogyitibor** [comment]
Hi Erich,

I has no opinion on Keil’s RTX .. it would be the first time I use it: but there are folks here around who are using it, under Keil’s MDK5, and they are happy with it. … at the same time I read some benchmark stuff about FreeRTOS, and although I did not find a direct comparison with RTX, the benchmarks were not very favorable for FreeRTOS…

So far, I thought – and your mail approves it – that it could be possible to make an RTX component for KDS / PEx. So, I took your articles ( including another one. CDE Hacking ), I already took your components, including FreeRTOS, (cand successfully used it ☺ ), and then started to make my own RTX component. Unfortunately a file structure which you describe in your articles has certainly changed: my KDE shows that my CDE User Component directory is C:\ProgramData\Processor Expert\PEXDRV_PE5_3\ , but, in fact, this folder does not exist at all: C:\ProgramData\Processor Expert\ contains only one folder, called PECache, and inside there are some “numbers only” named folders ( e.g. 76d83e5d – which makes me think about git commit identifiers…. ), which contains beancache and Config folders,…. So far, it seems to be rather complicated.

Anyway, I’ll try to follow your article about creating a component ( your is about an accelerometer, I’ll try to make an even simpler one, a LEDX component, for example ), and observe which files / folders are modified… I’ll let you know.

Thank you anyway for your help – and for your excellent blog

Cheers

Tibor

**Comment by ErichStyger** [comment]
As with any benchmark, the results heavily depend on the benchmark itself or how it is used (or what hidden agenda is behind the benchmark). Anyway...
C:\ProgramData\Processor Expert\PEXDRV_PE5_3 is still actively used. It is treated as 'legacy', but that way it works for any Eclipse or non-Eclipse environment.

I hope this helps,
Erich
